# -*- coding: utf-8 -*-
"""emotion detection 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iho_w7zKReDZyBwp32n_2fBE7SgcmLk1
"""

import kagglehub
path = kagglehub.dataset_download("samithsachidanandan/human-face-emotions")

import os
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    BatchNormalization,
    GlobalAveragePooling2D
)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.callbacks import (
    ModelCheckpoint,
    EarlyStopping,
    ReduceLROnPlateau
)

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input

from sklearn.utils.class_weight import compute_class_weight

base_path = path
image_root_dir = os.path.join(base_path, "Data") # Correct path to the root of image classes
print(f"Listing directories in {image_root_dir}:")
for expression in os.listdir(image_root_dir):
    class_path = os.path.join(image_root_dir, expression)
    if os.path.isdir(class_path): # Check if it's a directory (a class folder)
        num_images = len(os.listdir(class_path))
        print(f"{num_images} {expression} images")

from tensorflow.keras.preprocessing.image import load_img

pic_size = 256

plt.figure(0, figsize=(12,20))
cpt = 0

image_root_dir = os.path.join(base_path, "Data") # This is the correct root for classes
classes = sorted([d for d in os.listdir(image_root_dir) if os.path.isdir(os.path.join(image_root_dir, d))]) # Get actual class directories
# show up to 5 images per class, safe against small folders
for expression in classes:
    expr_dir = os.path.join(image_root_dir, expression) # Path to class directory
    image_files = sorted(os.listdir(expr_dir))
    if not image_files:
        continue
    sample_files = image_files[:5]  # pick first up-to-5 images
    for filename in sample_files:
        cpt += 1
        plt.subplot(len(classes), 5, cpt)
        img_path = os.path.join(expr_dir, filename)
        img = load_img(img_path, target_size=(pic_size, pic_size))
        plt.imshow(img)
        plt.axis('off')

plt.tight_layout()
plt.show()

IMG_SIZE = 100
BATCH_SIZE = 512
EPOCHS = 40

DATA_DIR = os.path.join(path, "Data")

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2,


    horizontal_flip=True
)

validation_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    color_mode="rgb",
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training",
    shuffle=True
)

validation_generator = validation_datagen.flow_from_directory(
    DATA_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    color_mode="rgb",
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation",
    shuffle=False
)

classes = train_generator.classes

weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(classes),
    y=classes
)

class_weights = dict(enumerate(weights))

print(class_weights)

base_model = ResNet50(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

# Fine-tune the top part only
for layer in base_model.layers[:-30]:
    layer.trainable = False

for layer in base_model.layers[-30:]:
    layer.trainable = True

inputs = Input(shape=(IMG_SIZE, IMG_SIZE, 3))

x = base_model(inputs, training=False)

x = GlobalAveragePooling2D()(x)

x = BatchNormalization()(x)

x = Dense(
    512,
    activation="relu"
)(x)

x = Dropout(0.5)(x)

outputs = Dense(
    train_generator.num_classes,
    activation="softmax"
)(x)

model = Model(inputs, outputs)

model.summary()

model.compile(

    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),

    loss="categorical_crossentropy",

    metrics=["accuracy"]
)

callbacks = [

    ModelCheckpoint(
        "best_resnet50.keras",
        monitor="val_accuracy",
        save_best_only=True,
        mode="max",
        verbose=1
    ),

    EarlyStopping(
        monitor="val_accuracy",
        patience=8,
        restore_best_weights=True,
        verbose=1
    ),

    ReduceLROnPlateau(
        monitor="val_accuracy",
        factor=0.5,
        patience=3,
        min_lr=1e-6,
        verbose=1
    )
]

history = model.fit(

    train_generator,

    validation_data=validation_generator,

    epochs=EPOCHS,

    class_weight=class_weights,

    callbacks=callbacks
)

model.save("emotion_resnet50.keras")

model_json = model.to_json()

with open("model.json", "w") as json_file:
    json_file.write(model_json)

print("Model saved successfully")

validation_generator.reset()

predictions = model.predict(
    validation_generator,
    verbose=1
)

y_pred = np.argmax(
    predictions,
    axis=1
)

y_true = validation_generator.classes

print(
    classification_report(
        y_true,
        y_pred,
        target_names=list(
            validation_generator.class_indices.keys()
        )
    )
)

print(
    "Accuracy:",
    accuracy_score(
        y_true,
        y_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_true,
        y_pred,
        average="weighted"
    )
)

print(
    "Recall:",
    recall_score(
        y_true,
        y_pred,
        average="weighted"
    )
)

print(
    "F1:",
    f1_score(
        y_true,
        y_pred,
        average="weighted"
    )
)

plt.figure(figsize=(20,10))

plt.subplot(1,2,1)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Loss")
plt.legend(["Train","Validation"])

plt.subplot(1,2,2)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Accuracy")
plt.legend(["Train","Validation"])

plt.show()

from google.colab import drive
drive.mount('/content/drive')
model.save('/content/drive/MyDrive/emotion_resnet50.keras')
model.save_weights('/content/drive/MyDrive/emotion_resnet50.weights.h5')

from tensorflow import keras

model = keras.models.load_model(
    "/content/drive/MyDrive/emotion_resnet50.keras"
)

import seaborn as sns
import matplotlib.pyplot as plt

predictions = model.predict(validation_generator)

y_pred = np.argmax(predictions, axis=1)
y_true = validation_generator.classes

class_names = list(validation_generator.class_indices.keys())

print("Accuracy:", accuracy_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred, average='weighted'))
print("Recall:", recall_score(y_true, y_pred, average='weighted'))
print("F1 Score:", f1_score(y_true, y_pred, average='weighted'))

print("\nClassification Report:\n")
print(
    classification_report(
        y_true,
        y_pred,
        target_names=class_names
    )
)

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10,8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()